# Add 'label1' to any changes within 'example' folder or any subfolders
frontend:
 - any: [frontend/**]

# Add 'label2' to any file changes within 'example2' folder
outside: 
 - any: [**/frontend]

# Add label3 to any change to .txt files within the entire repository. Quotation marks are required for the leading asterisk
a-joke:
- any: '**/*.txt'
