name: Integration Check

on:
  pull_request:
    branches: [develop]
    types: [opened]
    paths: ['frontend/**']

jobs:
   frontend_check:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Checks build
         uses: actions/setup-node@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           node-version: '18.x'    
       - name: Move to frontend
       - run: cd frontend
       - run: npm ci
       - run: npm run build
