name: Delete branch by label

on:
  push:
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Find and Delete Branch
        run: |
          # Get the most recently merged Pull Request
          PR_NUMBER=$(git log --merges --pretty=format:"%h %b" | grep 'Merge pull request #' | head -n 1 | awk '{print $5}' | sed 's/#//')
          
          # Get the labels of the Pull Request
          LABELS=$(gh pr view $PR_NUMBER --json labels -q .labels)
          
          # Check if the "delete branch" label exists
          if echo "$LABELS" | grep -q '"name": "delete branch"'; then
            # Extract the branch name from the PR
            BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)
            # Delete the branch
            git push origin --delete "$BRANCH_NAME"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ME_TOKEN }}
