name: Delete branch by label

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Detecting label
        if: contains(github.event.pull_request.labels.*.name, 'delete branch')
        run: echo Deleting branch
      - name: Delete branch
        run: |
          git push origin --delete $BRANCH_TO_DELETE
        env:
          BRANCH_TO_DELETE: ${{ github.event.pull_request.head.ref }}
